### ISSUE TITLE
Unnecessary unsafe `transmute` from `f32` to `u32`

### ISSUE THREAD

**Issue by yescallop** [sixpounder/quake-inverse-sqrt#1]
We have [`f32::to_bits`](https://doc.rust-lang.org/std/primitive.f32.html#method.to_bits) that does this safely.

**Comment by sixpounder** [comment]
Good point. Solved in [fb7ea7d](https://github.com/sixpounder/quake-inverse-sqrt/commit/fb7ea7d19ff96104e7a67a27325efe0939ba2011).

**Comment by yescallop** [comment]
By the way, we also have [`f32::from_bits`](https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits) :)

**Comment by sixpounder** [comment]
I already noticed and already done the commit :)

However, unless I am reading this wrong, these are all equivalent to `transmute`-ing, at the moment, so undefined behaviours scenarios kinda boil down to unchecked casts anyway.
